Init

diff --git a/.local/bin/monbright b/.local/bin/monbright
--- a/.local/bin/monbright
+++ b/.local/bin/monbright
@@ -5,21 +5,22 @@ monitor=$(xrandr --query | grep -i '\sconnected' | grep -i '[0-9]x[0-9]' | cut -
 [ -z "$monitor" ] && exit 1
 current_brightness=$(xrandr --verbose | grep -i "^$monitor connected" -A5 | grep -i "Brightness:" | cut -d ' ' -f2)
 [ -z "$current_brightness" ] && exit 1
-if [ "$#" -eq 2 ]; then
-    scale_change=$(echo "$2 / 100" | bc -l)
-    case "$1" in
-        "-inc") new_brightness=$(echo "$current_brightness + $scale_change" | bc -l) ;;
-        "-dec") new_brightness=$(echo "$current_brightness - $scale_change" | bc -l) ;;
-        *) echo "Invalid argument $1. Use -inc or -dec." && exit 1 ;;
-    esac
-    new_brightness=$(echo "if ($new_brightness > 1) 1 else if ($new_brightness < 0) 0 else $new_brightness" | bc -l)
-    xrandr --output "$monitor" --brightness "$new_brightness"
-    current_brightness=$(echo "$new_brightness * 100" | bc -l)
-else
-    current_brightness=$(echo "$current_brightness * 100" | bc -l)
-fi
-
 case "$monitor" in
     *eDP*|*LVDS*|*LFP*) printf "🪟%.0f%%\n" "$(xbacklight -get)" ;;
-    *) printf "🪟%.0f%%\n" "$current_brightness" ;;
+    *) 
+        if [ "$#" -eq 2 ]; then
+            scale_change=$(echo "$2 / 100" | bc -l)
+            case "$1" in
+                "-inc") new_brightness=$(echo "$current_brightness + $scale_change" | bc -l) ;;
+                "-dec") new_brightness=$(echo "$current_brightness - $scale_change" | bc -l) ;;
+                *) echo "Invalid argument $1. Use -inc or -dec." && exit 1 ;;
+            esac
+            new_brightness=$(echo "if ($new_brightness > 1) 1 else if ($new_brightness < 0) 0 else $new_brightness" | bc -l)
+            xrandr --output "$monitor" --brightness "$new_brightness"
+            current_brightness=$(echo "$new_brightness * 100" | bc -l)
+        else
+            current_brightness=$(echo "$current_brightness * 100" | bc -l)
+        fi
+        printf "🪟%.0f%%\n" "$current_brightness"
+        ;;
 esac
