Init

diff --git a/.local/bin/rbackup b/.local/bin/rbackup
--- a/.local/bin/rbackup
+++ b/.local/bin/rbackup
@@ -21,7 +21,7 @@ error() {
 	printf "%s\n" "$1" >&2
 	exit 1
 }
-   
+
 mount_luks() {
     if ! mount | grep -q " /mnt/extra "; then
         SIZE_NVME0=$(sudo blockdev --getsize64 /dev/nvme0n1p1)
@@ -46,8 +46,7 @@ sync_root() {
     ssh "$THESIAH_SERVER" "rm -rf /root/.config /var/www/thesiah"
     ssh "$THESIAH_SERVER" "mkdir -p /root/.config/bash /root/.config/shell /root/.config/vim /root/.local/bin /root/.local/share /root/.local/state /var/www/thesiah"
     sudo rm -rf /root/.config
-    sudo mkdir -p /root/.config/bash /root/.config/lf /root/.config/shell /root/.config/vim
-    sudo mkdir -p /root/.local/bin /root/.local/share /root/.local/state
+    sudo mkdir -p /root/.config/{bash,lf,shell,vim} /root/.local/{bin,share,state}
 
     # Root configuration synchronization on local system
     sudo rsync -vrazPlu --delete "$vim_path/vimrc" "/root/.config/vim/" >/dev/null 2>&1
@@ -83,11 +82,11 @@ sync_server() {
     rsync -vrazPlu --remove-source-files "$HOME/.cache/rootshortcutrc" "$THESIAH_SERVER:/root/.config/shell/"
 
     # Adding custom shortcuts to root's shell configuration on the remote system
-    ssh "$THESIAH_SERVER" "echo 'web=\"cd /var/www && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
-    ssh "$THESIAH_SERVER" "echo 'wen=\"cd /var/www/nextcloud && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
-    ssh "$THESIAH_SERVER" "echo 'wep=\"cd /var/www/prosody && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
-    ssh "$THESIAH_SERVER" "echo 'wet=\"cd /var/www/thesiah && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
-    ssh "$THESIAH_SERVER" "echo 'gng=\"cd /etc/nginx/sites-available && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
+    ssh "$THESIAH_SERVER" "echo 'web=\"cd /var/www && ls -A\" \\' >> /root/.config/shell/rootshortcutrc"
+    ssh "$THESIAH_SERVER" "echo 'wen=\"cd /var/www/nextcloud && ls -A\" \\' >> /root/.config/shell/rootshortcutrc" 
+    ssh "$THESIAH_SERVER" "echo 'wep=\"cd /var/www/prosody && ls -A\" \\' >> /root/.config/shell/rootshortcutrc"
+    ssh "$THESIAH_SERVER" "echo 'wet=\"cd /var/www/thesiah && ls -A\" \\' >> /root/.config/shell/rootshortcutrc"
+    ssh "$THESIAH_SERVER" "echo 'gng=\"cd /etc/nginx/sites-available && ls -A\" \\' >> /root/.config/shell/rootshortcutrc"
 
     # Sync Bash configuration
     rsync -vrazPlu --delete "$bash_path" "$THESIAH_SERVER:/root/.config/"
@@ -97,10 +96,23 @@ sync_server() {
     ssh "$THESIAH_SERVER" "source /root/.profile"
     
     # Sync for Git
-    ssh "$THESIAH_SERVER" "cp -r /root/.config /var/git/"
-    ssh "$THESIAH_SERVER" "chown -R git:git /var/git/.config/"
-    ssh "$THESIAH_GIT" "ln -sf /var/git/.config/bash/bash_profile /var/git/.profile"
-    ssh "$THESIAH_GIT" "source /var/git/.profile"
+    ssh "$THESIAH_SERVER" "cp -r /root/.config /var/www/git/"
+    ssh "$THESIAH_SERVER" "chown -R git:git /var/www/git/.config/"
+    ssh "$THESIAH_GIT" "ln -sf /var/www/git/.config/bash/bash_profile /var/www/git/.profile"
+    ssh "$THESIAH_GIT" "source /var/www/git/.profile"
+}
+
+sync_nextcloud() {
+    base="$(basename $backup_path)"
+    parent="$(dirname $backup_path)"
+    tmpdir="$(mktemp -d)"
+    pw="$(pass show server/nextcloud)"
+    cd "$tmpdir"
+    tar -C "$parent" -zcf "$base".tar.gz "$base"
+    rsync -vrazPlu --delete "$tmpdir/$base".tar.gz "$THESIAH_SERVER:/var/www/nextcloud/data/si@thesiah.xyz/files/backup/"
+    ssh "$THESIAH_SERVER" "chown -R www-date:www-data /var/www/nextcloud/data/si@thesiah.xyz/files/backup 2>/dev/null"
+    ssh "$THESIAH_SERVER" "cd /var/www/nextcloud && sudo -u www-data ./occ files:scan --path="/si@thesiah.xyz/files" 2>/dev/null"
+    rm -r "$tmpdir"
 }
 
 # mount_luks || error "Failed to mount $backup_path"
@@ -109,4 +121,5 @@ echo "Backup starts to $backup_path..."
 sync_files || error "Failed back up files"
 sync_root || error "Failed back up root"
 sync_server || error "Failed back up server"
+sync_nextcloud || error "Failed back up nextcloud"
 echo "Done!"
