Init

diff --git a/.local/bin/rbackup b/.local/bin/rbackup
--- a/.local/bin/rbackup
+++ b/.local/bin/rbackup
@@ -7,7 +7,7 @@ music_path="${XDG_MUSIC_DIR:-${HOME}/Music}"
 obsidian_path="$HOME/Obsidian"
 pass_path="${PASSWORD_STORE_DIR:-${XDG_DATA_HOME:-${HOME}/.local/share}/.password-store}"
 suck_path="${XDG_SOURCES_HOME:-${HOME}/.local/src}/suckless"
-web_path="${WEBDIR:-${HOME}/THESIAH}"
+web_path="${THESIAH_WWW:-${HOME}/THESIAH}"
 USER_HOME=$(eval echo ~"$USER")
 
 # targets
@@ -37,67 +37,72 @@ sync_files() {
     for source in "$dot_path" "$music_path" "$obsidian_path" "$pass_path" "$suck_path" "$web_path"; do
         rsync -vrazPlu --delete "$source" "$backup_path/" >/dev/null 2>&1 || {
             echo "Failed to sync $(basename "$source")"
-            exit 1
         }
     done
 }
 
 sync_root() {
     # clean targets
-    ssh "$THESIAH" "rm -rf /root/.config /var/www/thesiah"
-    ssh "$THESIAH" "mkdir -p /root/.config/bash /root/.config/shell /root/.config/vim /root/.local/bin /root/.local/share /root/.local/state /var/www/thesiah"
+    ssh "$THESIAH_SERVER" "rm -rf /root/.config /var/www/thesiah"
+    ssh "$THESIAH_SERVER" "mkdir -p /root/.config/bash /root/.config/shell /root/.config/vim /root/.local/bin /root/.local/share /root/.local/state /var/www/thesiah"
     sudo rm -rf /root/.config
     sudo mkdir -p /root/.config/bash /root/.config/lf /root/.config/shell /root/.config/vim
     sudo mkdir -p /root/.local/bin /root/.local/share /root/.local/state
 
     # Root configuration synchronization on local system
-    sudo rsync -vrazPlu --delete "$vim_path/vimrc" "/root/.config/vim/" >/dev/null 2>&1 || exit 1
-    sudo rsync -vrazPlu --delete "$lf_path" "/root/.config/" >/dev/null 2>&1 || exit 1
-    sudo mv -f "/root/.config/lf/rooticons" "/root/.config/lf/icons" >/dev/null 2>&1 || exit 1
-    sudo rsync -vrazPlu --delete "$bash_path" "/root/.config/" >/dev/null 2>&1 || exit 1
-    sudo rsync -vrazPlu --delete "$shell_path/inputrc" "/root/.config/shell/" >/dev/null 2>&1 || exit 1
+    sudo rsync -vrazPlu --delete "$vim_path/vimrc" "/root/.config/vim/" >/dev/null 2>&1
+    sudo rsync -vrazPlu --delete "$lf_path" "/root/.config/" >/dev/null 2>&1
+    sudo mv -f "/root/.config/lf/rooticons" "/root/.config/lf/icons" >/dev/null 2>&1
+    sudo rsync -vrazPlu --delete "$bash_path" "/root/.config/" >/dev/null 2>&1
+    sudo rsync -vrazPlu --delete "$shell_path/inputrc" "/root/.config/shell/" >/dev/null 2>&1
 
     # load shortcuts
     shortcuts >/dev/null 2>&1
 
     # Modify root's Bash and LF configuration to include user-specific settings
-    echo "[ -f \"$USER_HOME/.config/shell/shortcutrc\" ] && source \"$USER_HOME/.config/shell/shortcutrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1 || exit 1
-    echo "[ -f \"$USER_HOME/.config/shell/zshnameddirrc\" ] && source \"$USER_HOME/.config/shell/zshnameddirrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1 || exit 1
-    sudo sed -i "s|source \"~/.config/lf/shortcutrc\"|source \"$USER_HOME/.config/lf/shortcutrc\"|" /root/.config/lf/lfrc >/dev/null 2>&1 || exit 1
-    echo 'source "/root/.config/lf/rootshortcutrc"' | sudo tee -a /root/.config/lf/lfrc >/dev/null 2>&1 || exit 1
+    echo "[ -f \"$USER_HOME/.config/shell/shortcutrc\" ] && source \"$USER_HOME/.config/shell/shortcutrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1
+    echo "[ -f \"$USER_HOME/.config/shell/zshnameddirrc\" ] && source \"$USER_HOME/.config/shell/zshnameddirrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1
+    sudo sed -i "s|source \"~/.config/lf/shortcutrc\"|source \"$USER_HOME/.config/lf/shortcutrc\"|" /root/.config/lf/lfrc >/dev/null 2>&1
+    echo 'source "/root/.config/lf/rootshortcutrc"' | sudo tee -a /root/.config/lf/lfrc >/dev/null 2>&1
 
     # Final ownership and link adjustments
-    sudo chown -R root:root /root/.config/ >/dev/null 2>&1 || exit 1
-    sudo ln -sf /root/.config/bash/bashrc /root/.bashrc >/dev/null 2>&1 || exit 1
-    sudo ln -sf /root/.config/bash/bash_profile /root/.bash_profile >/dev/null 2>&1 || exit 1
-    sudo ln -sf /root/.config/shell/inputrc /root/.inputrc >/dev/null 2>&1 || exit 1
-    sudo ln -sf /root/.config/vim/vimrc /root/.vimrc >/dev/null 2>&1 || exit 1
+    sudo chown -R root:root /root/.config/ >/dev/null 2>&1
+    sudo ln -sf /root/.config/bash/bashrc /root/.bashrc >/dev/null 2>&1
+    sudo ln -sf /root/.config/bash/bash_profile /root/.bash_profile >/dev/null 2>&1
+    sudo ln -sf /root/.config/shell/inputrc /root/.inputrc >/dev/null 2>&1
+    sudo ln -sf /root/.config/vim/vimrc /root/.vimrc >/dev/null 2>&1
 }
 
 sync_server() {
     # Sync operations with explicit error checking
-    rsync -vrazPlu --delete "$thesiah_path/" "$THESIAH:/var/www/thesiah/" >/dev/null 2>&1 || exit 1
-    rsync -vrazPlu --delete "$vim_path/vimrc" "$THESIAH:/root/.config/vim/" >/dev/null 2>&1 || exit 1
-    rsync -vrazPlu --delete "$shell_path/inputrc" "$THESIAH:/root/.config/shell/" >/dev/null 2>&1 || exit 1
-    sudo cp /root/.config/shell/rootshortcutrc ~/.cache/ >/dev/null 2>&1 || exit 1
-    sudo chown -R "$USER":wheel ~/.cache/rootshortcutrc >/dev/null 2>&1 || exit 1
-    rsync -vrazPlu --remove-source-files "$HOME/.cache/rootshortcutrc" "$THESIAH:/root/.config/shell/" >/dev/null 2>&1 || exit 1
+    rsync -vrazPlu --delete "$thesiah_path/" "$THESIAH_SERVER:/var/www/thesiah/"
+    rsync -vrazPlu --delete "$vim_path/vimrc" "$THESIAH_SERVER:/root/.config/vim/"
+    rsync -vrazPlu --delete "$shell_path/inputrc" "$THESIAH_SERVER:/root/.config/shell/"
+    sudo cp /root/.config/shell/rootshortcutrc ~/.cache/
+    sudo chown -R "$USER":wheel ~/.cache/rootshortcutrc
+    rsync -vrazPlu --remove-source-files "$HOME/.cache/rootshortcutrc" "$THESIAH_SERVER:/root/.config/shell/"
 
     # Adding custom shortcuts to root's shell configuration on the remote system
-    ssh "$THESIAH" "echo 'web=\"cd /var/www && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
-    ssh "$THESIAH" "echo 'wen=\"cd /var/www/nextcloud && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
-    ssh "$THESIAH" "echo 'wep=\"cd /var/www/prosody && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
-    ssh "$THESIAH" "echo 'wet=\"cd /var/www/thesiah && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
+    ssh "$THESIAH_SERVER" "echo 'web=\"cd /var/www && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
+    ssh "$THESIAH_SERVER" "echo 'wen=\"cd /var/www/nextcloud && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
+    ssh "$THESIAH_SERVER" "echo 'wep=\"cd /var/www/prosody && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
+    ssh "$THESIAH_SERVER" "echo 'wet=\"cd /var/www/thesiah && ls -A\" ' >> /root/.config/shell/rootshortcutrc"
 
     # Sync Bash configuration
-    rsync -vrazPlu --delete "$bash_path" "$THESIAH:/root/.config/" >/dev/null 2>&1 || exit 1
-    ssh "$THESIAH" "chown -R root:root /var/www/thesiah" >/dev/null 2>&1 || exit 1
-    ssh "$THESIAH" "chown -R root:root /root/.config/" >/dev/null 2>&1 || exit 1
-    ssh "$THESIAH" "ln -sf /root/.config/bash/bash_profile /root/.profile" >/dev/null 2>&1 || exit 1
-    ssh "$THESIAH" "source /root/.profile" >/dev/null 2>&1 || exit 1
+    rsync -vrazPlu --delete "$bash_path" "$THESIAH_SERVER:/root/.config/"
+    ssh "$THESIAH_SERVER" "chown -R root:root /var/www/thesiah"
+    ssh "$THESIAH_SERVER" "chown -R root:root /root/.config/"
+    ssh "$THESIAH_SERVER" "ln -sf /root/.config/bash/bash_profile /root/.profile"
+    ssh "$THESIAH_SERVER" "source /root/.profile"
+    
+    # Sync for Git
+    ssh "$THESIAH_SERVER" "cp -r /root/.config /var/git/"
+    ssh "$THESIAH_SERVER" "chown -R git:git /var/git/.config/"
+    ssh "$THESIAH_GIT" "ln -sf /var/git/.config/bash/bash_profile /var/git/.profile"
+    ssh "$THESIAH_GIT" "source /var/git/.profile"
 }
 
-mount_luks || error "Failed to mount $backup_path"
+# mount_luks || error "Failed to mount $backup_path"
 echo "Backup starts to $backup_path..."
 [ -d "$backup_path" ] || mkdir -p "$backup_path"
 sync_files || error "Failed back up files"
