Updates

diff --git a/.local/bin/rbackup b/.local/bin/rbackup
--- a/.local/bin/rbackup
+++ b/.local/bin/rbackup
@@ -10,18 +10,6 @@ suck_path="${XDG_SOURCES_HOME:-${HOME}/.local/src}/suckless"
 web_path="${WEBDIR:-${HOME}/THESIAH}"
 USER_HOME=$(eval echo ~"$USER")
 
-echo "Backup files to $backup_path..."
-
-[ -d "$backup_path" ] || mkdir -p "$backup_path"
-
-# Using a loop over space-separated strings instead of an array
-for source in "$dot_path" "$music_path" "$obsidian_path" "$pass_path" "$suck_path" "$web_path"; do
-	rsync -vrazPlu --delete "$source" "$backup_path/" >/dev/null 2>&1 || {
-		echo "Failed to sync $(basename "$source")"
-		exit 1
-	}
-done
-
 # targets
 bash_path="${XDG_DOTFILES_DIR:-${HOME}/.dotfiles}/.config/bash"
 shell_path="${XDG_DOTFILES_DIR:-${HOME}/.dotfiles}/.config/shell"
@@ -29,55 +17,90 @@ vim_path="${XDG_DOTFILES_DIR:-${HOME}/.dotfiles}/.config/vim"
 thesiah_path="$web_path/public"
 lf_path="${XDG_DOTFILES_DIR:-${HOME}/.dotfiles}/.config/lf"
 
-# clean targets
-ssh "$THESIAH" "rm -rf /root/.config /var/www/thesiah"
-ssh "$THESIAH" "mkdir -p /root/.config/bash /root/.config/shell /root/.config/vim /root/.local/bin /root/.local/share /root/.local/state /var/www/thesiah"
-sudo rm -rf /root/.config
-sudo mkdir -p /root/.config/bash /root/.config/lf /root/.config/shell /root/.config/vim
-sudo mkdir -p /root/.local/bin /root/.local/share /root/.local/state
+error() {
+	printf "%s\n" "$1" >&2
+	exit 1
+}
+   
+mount_luks() {
+    if ! mount | grep -q " /mnt/extra "; then
+        SIZE_NVME0=$(sudo blockdev --getsize64 /dev/nvme0n1p1)
+        SIZE_NVME1=$(sudo blockdev --getsize64 /dev/nvme1n1p1)
+        [ "$SIZE_NVME1" -lt "$SIZE_NVME0" ] && TARGET_DEVICE="/dev/nvme0n1p1" || TARGET_DEVICE="/dev/nvme1n1p1"
+        ${TERMINAL:-st} -n floatterm -g 60x1 -e sudo cryptsetup open "$TARGET_DEVICE" "extra"
+        sudo -A mount "/dev/mapper/extra" "/mnt/extra" -o uid="$(id -u)",gid="$(id -g)" || sudo -A mount "/dev/mapper/extra" "/mnt/extra"
+    fi
+}
 
-# Root configuration synchronization on local system
-sudo rsync -vrazPlu --delete "$vim_path/vimrc" "/root/.config/vim/" >/dev/null 2>&1 || exit 1
-sudo rsync -vrazPlu --delete "$lf_path" "/root/.config/" >/dev/null 2>&1 || exit 1
-sudo mv -f "/root/.config/lf/rooticons" "/root/.config/lf/icons" >/dev/null 2>&1 || exit 1
-sudo rsync -vrazPlu --delete "$bash_path" "/root/.config/" >/dev/null 2>&1 || exit 1
-sudo rsync -vrazPlu --delete "$shell_path/inputrc" "/root/.config/shell/" >/dev/null 2>&1 || exit 1
+# Using a loop over space-separated strings instead of an array
+sync_files() {
+    for source in "$dot_path" "$music_path" "$obsidian_path" "$pass_path" "$suck_path" "$web_path"; do
+        rsync -vrazPlu --delete "$source" "$backup_path/" >/dev/null 2>&1 || {
+            echo "Failed to sync $(basename "$source")"
+            exit 1
+        }
+    done
+}
 
-# load shortcuts
-shortcuts >/dev/null 2>&1
+sync_root() {
+    # clean targets
+    ssh "$THESIAH" "rm -rf /root/.config /var/www/thesiah"
+    ssh "$THESIAH" "mkdir -p /root/.config/bash /root/.config/shell /root/.config/vim /root/.local/bin /root/.local/share /root/.local/state /var/www/thesiah"
+    sudo rm -rf /root/.config
+    sudo mkdir -p /root/.config/bash /root/.config/lf /root/.config/shell /root/.config/vim
+    sudo mkdir -p /root/.local/bin /root/.local/share /root/.local/state
 
-# Modify root's Bash and LF configuration to include user-specific settings
-echo "[ -f \"$USER_HOME/.config/shell/shortcutrc\" ] && source \"$USER_HOME/.config/shell/shortcutrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1 || exit 1
-echo "[ -f \"$USER_HOME/.config/shell/zshnameddirrc\" ] && source \"$USER_HOME/.config/shell/zshnameddirrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1 || exit 1
-sudo sed -i "s|source \"~/.config/lf/shortcutrc\"|source \"$USER_HOME/.config/lf/shortcutrc\"|" /root/.config/lf/lfrc >/dev/null 2>&1 || exit 1
-echo 'source "/root/.config/lf/rootshortcutrc"' | sudo tee -a /root/.config/lf/lfrc >/dev/null 2>&1 || exit 1
+    # Root configuration synchronization on local system
+    sudo rsync -vrazPlu --delete "$vim_path/vimrc" "/root/.config/vim/" >/dev/null 2>&1 || exit 1
+    sudo rsync -vrazPlu --delete "$lf_path" "/root/.config/" >/dev/null 2>&1 || exit 1
+    sudo mv -f "/root/.config/lf/rooticons" "/root/.config/lf/icons" >/dev/null 2>&1 || exit 1
+    sudo rsync -vrazPlu --delete "$bash_path" "/root/.config/" >/dev/null 2>&1 || exit 1
+    sudo rsync -vrazPlu --delete "$shell_path/inputrc" "/root/.config/shell/" >/dev/null 2>&1 || exit 1
 
-# Final ownership and link adjustments
-sudo chown -R root:root /root/.config/ >/dev/null 2>&1 || exit 1
-sudo ln -sf /root/.config/bash/bashrc /root/.bashrc >/dev/null 2>&1 || exit 1
-sudo ln -sf /root/.config/bash/bash_profile /root/.bash_profile >/dev/null 2>&1 || exit 1
-sudo ln -sf /root/.config/shell/inputrc /root/.inputrc >/dev/null 2>&1 || exit 1
-sudo ln -sf /root/.config/vim/vimrc /root/.vimrc >/dev/null 2>&1 || exit 1
+    # load shortcuts
+    shortcuts >/dev/null 2>&1
 
-# Sync operations with explicit error checking
-rsync -vrazPlu --delete "$thesiah_path/" "$THESIAH:/var/www/thesiah/" >/dev/null 2>&1 || exit 1
-rsync -vrazPlu --delete "$vim_path/vimrc" "$THESIAH:/root/.config/vim/" >/dev/null 2>&1 || exit 1
-rsync -vrazPlu --delete "$shell_path/inputrc" "$THESIAH:/root/.config/shell/" >/dev/null 2>&1 || exit 1
-sudo cp /root/.config/shell/rootshortcutrc ~/.cache/ >/dev/null 2>&1 || exit 1
-sudo chown -R "$USER":wheel ~/.cache/rootshortcutrc >/dev/null 2>&1 || exit 1
-rsync -vrazPlu --remove-source-files "$HOME/.cache/rootshortcutrc" "$THESIAH:/root/.config/shell/" >/dev/null 2>&1 || exit 1
+    # Modify root's Bash and LF configuration to include user-specific settings
+    echo "[ -f \"$USER_HOME/.config/shell/shortcutrc\" ] && source \"$USER_HOME/.config/shell/shortcutrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1 || exit 1
+    echo "[ -f \"$USER_HOME/.config/shell/zshnameddirrc\" ] && source \"$USER_HOME/.config/shell/zshnameddirrc\"" | sudo tee -a /root/.config/bash/bashrc >/dev/null 2>&1 || exit 1
+    sudo sed -i "s|source \"~/.config/lf/shortcutrc\"|source \"$USER_HOME/.config/lf/shortcutrc\"|" /root/.config/lf/lfrc >/dev/null 2>&1 || exit 1
+    echo 'source "/root/.config/lf/rootshortcutrc"' | sudo tee -a /root/.config/lf/lfrc >/dev/null 2>&1 || exit 1
 
-# Adding custom shortcuts to root's shell configuration on the remote system
-ssh "$THESIAH" "echo 'web=\"cd /var/www && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
-ssh "$THESIAH" "echo 'wen=\"cd /var/www/nextcloud && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
-ssh "$THESIAH" "echo 'wep=\"cd /var/www/prosody && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
-ssh "$THESIAH" "echo 'wet=\"cd /var/www/thesiah && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
+    # Final ownership and link adjustments
+    sudo chown -R root:root /root/.config/ >/dev/null 2>&1 || exit 1
+    sudo ln -sf /root/.config/bash/bashrc /root/.bashrc >/dev/null 2>&1 || exit 1
+    sudo ln -sf /root/.config/bash/bash_profile /root/.bash_profile >/dev/null 2>&1 || exit 1
+    sudo ln -sf /root/.config/shell/inputrc /root/.inputrc >/dev/null 2>&1 || exit 1
+    sudo ln -sf /root/.config/vim/vimrc /root/.vimrc >/dev/null 2>&1 || exit 1
+}
 
-# Sync Bash configuration
-rsync -vrazPlu --delete "$bash_path" "$THESIAH:/root/.config/" >/dev/null 2>&1 || exit 1
-ssh "$THESIAH" "chown -R root:root /var/www/thesiah" >/dev/null 2>&1 || exit 1
-ssh "$THESIAH" "chown -R root:root /root/.config/" >/dev/null 2>&1 || exit 1
-ssh "$THESIAH" "ln -sf /root/.config/bash/bash_profile /root/.profile" >/dev/null 2>&1 || exit 1
-ssh "$THESIAH" "source /root/.profile" >/dev/null 2>&1 || exit 1
+sync_server() {
+    # Sync operations with explicit error checking
+    rsync -vrazPlu --delete "$thesiah_path/" "$THESIAH:/var/www/thesiah/" >/dev/null 2>&1 || exit 1
+    rsync -vrazPlu --delete "$vim_path/vimrc" "$THESIAH:/root/.config/vim/" >/dev/null 2>&1 || exit 1
+    rsync -vrazPlu --delete "$shell_path/inputrc" "$THESIAH:/root/.config/shell/" >/dev/null 2>&1 || exit 1
+    sudo cp /root/.config/shell/rootshortcutrc ~/.cache/ >/dev/null 2>&1 || exit 1
+    sudo chown -R "$USER":wheel ~/.cache/rootshortcutrc >/dev/null 2>&1 || exit 1
+    rsync -vrazPlu --remove-source-files "$HOME/.cache/rootshortcutrc" "$THESIAH:/root/.config/shell/" >/dev/null 2>&1 || exit 1
 
+    # Adding custom shortcuts to root's shell configuration on the remote system
+    ssh "$THESIAH" "echo 'web=\"cd /var/www && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
+    ssh "$THESIAH" "echo 'wen=\"cd /var/www/nextcloud && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
+    ssh "$THESIAH" "echo 'wep=\"cd /var/www/prosody && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
+    ssh "$THESIAH" "echo 'wet=\"cd /var/www/thesiah && ls -A\" ' >> /root/.config/shell/rootshortcutrc" >/dev/null 2>&1 || exit 2
+
+    # Sync Bash configuration
+    rsync -vrazPlu --delete "$bash_path" "$THESIAH:/root/.config/" >/dev/null 2>&1 || exit 1
+    ssh "$THESIAH" "chown -R root:root /var/www/thesiah" >/dev/null 2>&1 || exit 1
+    ssh "$THESIAH" "chown -R root:root /root/.config/" >/dev/null 2>&1 || exit 1
+    ssh "$THESIAH" "ln -sf /root/.config/bash/bash_profile /root/.profile" >/dev/null 2>&1 || exit 1
+    ssh "$THESIAH" "source /root/.profile" >/dev/null 2>&1 || exit 1
+}
+
+mount_luks || error "Failed to mount $backup_path"
+echo "Backup starts to $backup_path..."
+[ -d "$backup_path" ] || mkdir -p "$backup_path"
+sync_files || error "Failed back up files"
+sync_root || error "Failed back up root"
+sync_server || error "Failed back up server"
 echo "Done!"
