Init

diff --git a/.local/bin/rbackup b/.local/bin/rbackup
--- a/.local/bin/rbackup
+++ b/.local/bin/rbackup
@@ -116,10 +116,10 @@ sync_nextcloud() {
 }
 
 echo "Backup starts to $backup_path..."
-mount_luks && echo "Mount backup drive.. " && echo "Success to mount luks drive" || error "Failed to mount $backup_path"
+mount_luks && echo "Mount backup drive.. " && echo "Success to mount luks drive!" || error "Failed to mount $backup_path"
 [ -d "$backup_path" ] || mkdir -p "$backup_path"
-sync_files && echo "Sync home files..." && echo "Success to sync files" || error "Failed back up files"
-sync_root && echo "Sync root files..." && echo "Success to sync root" || error "Failed back up root"
-sync_server && echo "Sync server files..." && echo "Success to sync server" || error "Failed back up server"
-sync_nextcloud && echo "Sync files to nextcloud" && echo "Success to sync nextcloud" || error "Failed back up nextcloud"
+sync_files && echo "Sync home files..." && echo "Success to sync files!" || error "Failed back up files"
+sync_root && echo "Sync root files..." && echo "Success to sync root!" || error "Failed back up root"
+sync_server && echo "Sync server files..." && echo "Success to sync server!" || error "Failed back up server"
+sync_nextcloud && echo "Sync files to nextcloud..." && echo "Success to sync nextcloud!" || error "Failed back up nextcloud"
 echo "Done!"
